export { default as App } from './app'
export { default as Controls } from './controls/controls'
export { default as Word } from './word/word'
export { default as Prompt } from './prompt/prompt'
export { default as Score } from './score/score'
export { default as Timer } from './timer/timer'
export { default as TypingBox } from './typing-box/typing-box'
